pipeline:
  restore-cache:
    image: node:16
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  install:
    image: node:16
    commands:
      - npm install
  test-build:
    image: node:16
    group: test
    commands:
      - npm build
  unit-tests:
    image: node:16
    group: test
    commands:
      - npm test