---
kind: pipeline
name: default

steps:
- name: install
  pull: if-not-exists
  image: node:16
  commands:
  - npm install
  
- name: test-build
  pull: if-not-exists
  image: node:16
  commands:
  - npm run build

- name: unit-tests
  pull: if-not-exists
  image: node:16
  commands:
  - npm run test



